export const GAME_CONSTANTS = {
	GRID_SIZE: 9,
	BOX_SIZE: 3,
	TOTAL_CELLS: 81,
	SCORING: {
		CORRECT_MOVE: 5,
		ERROR_PENALTY: -1,
		INITIAL_HINT_PENALTY: 3,
		STARTING_HINTS: 10,
		MAX_TIME_BONUS: 500,
	},
	VISIBLE_CELLS: {
		BEGINNER: { MIN: 36, MAX: 40 },
		INTERMEDIATE: { MIN: 32, MAX: 36 },
		HARD: { MIN: 28, MAX: 32 },
		EXPERT: { MIN: 24, MAX: 28 },
	},
} as const;
